### ISSUE TITLE
[PE-D][Tester C] No feature to delete or edit grade for a student.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-1/tp#171]
Perhaps can consider implementing a feature to delete or edit grade for a student as it might be useful for users

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: agarwal-anjali/ped#6

**Comment by e1010101** [comment]
Not sure if this can be added for v1.4, but can be KIV for the far future.

**Comment by Hoodineee** [comment]
To edit a grade for a certain assessment of a subject, the user will have to use the grade command with the subject and assessment name that the user would like to edit. It will overwrite the previous grade for that assessment for the subject. As for delete, due to feature freeze, we are unable to add that in. However, the user can edit the assessment to have a weightage of 0 which will remove the assessment from being part of the students grade.
